# Generated by Django 4.1.7 on 2023-03-04 03:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='features',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='listing.listingfeature'),
        ),
    ]
