# Generated by Django 4.1.7 on 2023-03-07 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0002_listing_features'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='features',
        ),
        migrations.AddField(
            model_name='listing',
            name='cctv',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='listing',
            name='elevator',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='listing',
            name='furnished',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='listing',
            name='parking',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='listing',
            name='pool',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='listing',
            name='rooms',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='wifi',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='ListingFeature',
        ),
    ]
